name: Update Leaderboard And Beaten Modes List

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Chromium
        run: python -m playwright install --with-deps chromium

      - name: Test API access
        run: |
          python - <<'PY'
          import asyncio
          from playwright.async_api import async_playwright

          URL = "https://aml-api-eta.vercel.app/clans/1a68233f-ae59-431b-ba1b-e458b548acfa/members"

          async def main():
              async with async_playwright() as p:
                  browser = await p.chromium.launch()
                  page = await browser.new_page()

                  response = await page.goto(
                      URL,
                      wait_until="domcontentloaded",
                      timeout=30000
                  )

                  print("Status:", response.status if response else None)
                  print("Title:", await page.title())
                  print("Body:")
                  print((await page.locator("body").inner_text())[:1000])

                  await browser.close()

          asyncio.run(main())
          PY

      - name: Run the leaderboard script
        run: python scripts/leaderboard.py

      - name: Run the countries script
        run: python scripts/countries.py

      - name: Run the beaten modes script
        run: python scripts/beatenmodes.py

      - name: Show diff
        run: |
          git status
          git diff

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resources
          git commit -m "Update leaderboard" || echo "No changes"
          git push